version: "3.3"
services:
  mariadb:
    container_name: mariadb
    image: mariadb
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: example
  adminer:
    container_name: adminer
    image: adminer
    ports:
      - 8080:8080
